# NY-24 Campaign Infrastructure Docker Compose Configuration
version: '3.8'

services:
  ny24-campaign-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:/app/data/ny24_campaign.db
    volumes:
      - campaign_data:/app/data
      - campaign_uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - campaign_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - campaign_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ny24-campaign-app
    restart: unless-stopped
    networks:
      - campaign_network

  backup:
    image: alpine:latest
    volumes:
      - campaign_data:/backup/data:ro
      - ./backups:/backup/output
    command: |
      sh -c "
        apk add --no-cache sqlite &&
        while true; do
          sqlite3 /backup/data/ny24_campaign.db '.backup /backup/output/backup_$(date +%Y%m%d_%H%M%S).db' &&
          find /backup/output -name '*.db' -mtime +7 -delete &&
          sleep 3600
        done
      "
    restart: unless-stopped

volumes:
  campaign_data:
  campaign_uploads:
  redis_data:

networks:
  campaign_network:
    driver: bridge