# Railway Deployment Configuration
# Deploy with: railway up

[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 30
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

[env]
  NODE_ENV = "production"
  PORT = { default = "8080" }
  
# These will be set in Railway dashboard as secrets
# DATABASE_URL - Railway PostgreSQL connection string
# SESSION_SECRET - Strong random string
# NEWS_API_KEY - NewsAPI key for briefings
# SQUARE_ACCESS_TOKEN - Square payment processing
# SLACK_WEBHOOK_URL - Deployment notifications